name: Typo Check

on: [pull_request]

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
